### ISSUE TITLE
Workperiods for RB with status 'cancelled' are displaying in the Admin app

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#10]
Description:

1. Now workperiods for RB with status 'cancelled' are displaying in the Admin app. If so, then it is possible for the Admin to process payment for the resources who are cancelled. Can we put some restriction to prevent cancelled RB's data showing up in Admin app?

![image](https://user-images.githubusercontent.com/55895538/120420175-cf979900-c39e-11eb-9fc1-db53b9b4f19f.png)

![image](https://user-images.githubusercontent.com/55895538/120420131-ba226f00-c39e-11eb-8862-f735b473d5a8.png)

2. Also for RB's with status 'closed', Currently if payment not done (paymentStatus='pending') but RB closed, those records are also showing up. Do we need add any restriction for that also?

3. Still I am able to see some records with older status 'sourcing', 'in-review' displaying in Admin app.
![image](https://user-images.githubusercontent.com/55895538/120420539-80059d00-c39f-11eb-8aa5-af7f4c7d4905.png)

cc: @nkumar-topcoder

**Comment by maxceem** [comment]
This is fixed now, and only `placed` Resource Bookings are shown in this table.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/120782770-4e3e3300-c565-11eb-9eaa-a2737b4d00f4.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
