### ISSUE TITLE
Filter by Topcoder Handle issues

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#11]
Description:

1. Filter by Topcoder Handle is case sensitive, it is displaying records from RB table but not displaying records from WorkPeriod table.

<img width="960" alt="case_sensitive_1" src="https://user-images.githubusercontent.com/55895538/120427768-800c9980-c3ad-11eb-8d49-bd3701d69641.png">
<img width="948" alt="case_sensitive_2" src="https://user-images.githubusercontent.com/55895538/120427775-83a02080-c3ad-11eb-8107-91aa64bc4545.png">

2. At Present, records are filtered automatically if user enters the correct Topcoder handle without clicking 'Search icon' (It's inactive now) or clicking 'enter' button from Keyboard. Should we support filtering only after clicking 'search' icon/pressing 'Enter' from keyboard to prevent confusion?

3. If user clicks 'Enter' from keyboard after entering userhandle, Whole page is getting reloaded and the filter is gone. But in url the filter by Topcoder handle is displayed(https://platform.topcoder-dev.com/taas-admin/work-periods?topcoder_handle=Aditya65#)  which is normally not displayed if 'Entered' not clicked.

<img width="956" alt="enter_search_topcoder_issue" src="https://user-images.githubusercontent.com/55895538/120428249-4be5a880-c3ae-11eb-911d-2943b7efd7f2.png">

https://user-images.githubusercontent.com/55895538/120428475-a848c800-c3ae-11eb-97b1-5baff6d8d2e0.mp4

**Comment by maxceem** [comment]
@sandhiyakavi this is fixed and ready for QA.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Records are getting displayed irrespective of the letter case.

![image](https://user-images.githubusercontent.com/55895538/120605149-b3702680-c488-11eb-8c19-7937d8b30dae.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
