### ISSUE TITLE
Typo in the role created message

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-taas-admin-app#110]
**Steps**

Go to TAAS Admin >> Roles
Create a new role
Check the message

![image](https://user-images.githubusercontent.com/4592712/127981547-e9ca1e48-b201-4a6b-82f0-bf2716b350f2.png)

**Comment by lakshmiathreya** [comment]
Verified Role creation message in Prod.
<img width="1680" alt="Screenshot 2021-08-16 at 6 12 40 PM" src="https://user-images.githubusercontent.com/51733042/129565531-c816708a-d625-4d48-88b3-9507a93ca3f3.png">
