### ISSUE TITLE
Simple CRUD interface for Role Management

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/micro-frontends-taas-admin-app#111]
Build a simple CRUD tool inside the TaaS Admin tab of platform.topcoder.com which allows admins to edit the taas-role data.

Must allow creation of a new role, and deletion of an existing role.

Following fields are must haves:
- Role Name
- Job Description (WYSIWYG editor ideally, but focus on compatibility with the existing display in the UI)
- Skills (include typeahead/validation against the endpoint)
- Number of Members
- Number of Available Members
- All rate values
- Image URL (If this is necessary - Atif make the call on this)
- Time to Candidates
- Time to Interview

**Comment by sdgun** [comment]
Verified in production.

<img width="1680" alt="Screenshot 2021-08-16 at 3 32 46 PM" src="https://user-images.githubusercontent.com/4592712/129558810-25ee68de-f16c-44f3-9455-70ebbc35a4f0.png">

**Comment by lakshmiathreya** [comment]
-- Delete and Sync verified in Prod.
