### ISSUE TITLE
Records/Page filter is not getting cleared on applying 'Clear Filter' button

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#12]
Description:
Records/Page filter is not getting cleared on applying 'Clear Filter' button

https://user-images.githubusercontent.com/55895538/120429139-dda1e580-c3af-11eb-9812-f3c6a0adee8a.mp4

**Comment by maxceem** [comment]
I think it's expected behavior. Sorting also stays.

We have to only go to the first page when we clear filter because the results are changed. The same way we have to reset page to 1 when we change the sort order, but we don't have to reset per page.
