### ISSUE TITLE
Clicking Topcoder handle displays blank page if RB status is not 'placed'

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#13]
Description:
Clicking Topcoder handle displays blank page if RB status is 'closed'/'cancelled'  (other than 'placed') since only RB with status 'placed' is viewable in Taas app. 

Can we display message like 'Closed/Cancelled ResourceBookings cannot be viewed' ?

![image](https://user-images.githubusercontent.com/55895538/120438485-67f04680-c3bc-11eb-9130-30cc239e7fa9.png)

**Comment by maxceem** [comment]
@sandhiyakavi as this is issue in TaaS App, can we move it to the TaaS App.

And regarding this link, in Admin App, I guess instead of pointing it to Resource Booking, we can point it to the member page, which exists for any use, what do you think?

**Comment by sandhiyakavi** [comment]
@maxceem Yes, We can point it to the member page 

Also there is no way to access this page in Taas app, until we hit directly through url. Do we need to make it as an issue in Taas app?

**Comment by maxceem** [comment]
> Also there is no way to access this page in Taas app, until we hit directly through url. Do we need to make it as an issue in Taas app?

We have a way to access this page for in TaaS API for placed RB from here https://platform.topcoder-dev.com/taas/myteams/17717

I've fixed Admin App to show only `placed` Resource Bookings so this issue should never happen again when we click users from Admin App.

**Comment by sandhiyakavi** [comment]
Issue resolved through https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/10
