### ISSUE TITLE
[$10] Fix Prop Types Warnings

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#16]
Fix all the Prop Type warnings shown in browser console.

![image](https://user-images.githubusercontent.com/146016/120600149-1a71e900-c451-11eb-99bf-12ce33ec41f3.png)
![image](https://user-images.githubusercontent.com/146016/120600177-2198f700-c451-11eb-9c67-ad419ede4156.png)
![image](https://user-images.githubusercontent.com/146016/120600190-26f64180-c451-11eb-9e3d-c4abaef1ca4c.png)

**Comment by maxceem** [comment]
@MadOPcode one more small issue is ready to pick up if you like.

**Comment by MadOPcode** [comment]
@maxceem created a PR (but it looks like it is already mentioned in this thread).

**Comment by MadOPcode** [comment]
@maxceem is there something that I've missed? Why is this issue re-opened?

**Comment by maxceem** [comment]
No, all good, I opened it to track the issues where I have to process payments.
It was closed automatically because the Pull Request https://github.com/topcoder-platform/micro-frontends-taas-admin-app/pull/18 has text `Fixes #16` which triggered automatic issue closing. Usually I close issues manually after they pass QA and payment is processed.

**Comment by maxceem** [comment]
This is just code quality issue, and cannot be QAed, so closing.
