### ISSUE TITLE
Nice to have: Weekly rate show as $0 instead of hyphen if not present

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#17]
Description:

It woult be nice to show Weekly rate as $0 instead of hyphen if not present.

![image](https://user-images.githubusercontent.com/55895538/120608856-9b020b00-c48c-11eb-80c2-0503720df65e.png)

**Comment by maxceem** [comment]
@sandhiyakavi IMHO it would be better to keep it `-`. 
- `-` means no member rate is set
- `0` means member rate is set to `0` theoretically we could you use it for something.

But I could be wrong. I suggest to leave it as it is for now, and wait for the feedback from admins if they prefer the other way.
