### ISSUE TITLE
[$30] When update "Working Days" we have to update other Work Period values in the table

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#25]
When we update  the value inside `Working Days` we send request to the server to update. When this value is updated it could happen that other values of the Work Period would be updated automatically.

So when Work Period working days is updated we have to update all other fields using response from the server.

For example, when we update Working Days to `0`, then `pyamentStatus` would be updated on the server to `No Days`, so we should see this update reflected in the table as soon as we get response from the server

![image](https://user-images.githubusercontent.com/146016/122216470-1ca65f80-ceb5-11eb-8d93-5cdc20754707.png)

**Comment by maxceem** [comment]
This works perfectly https://monosnap.com/file/vbFKeWaR07Hl189mXGfCqmqpA2hxbb

**Comment by maxceem** [comment]
paid via https://www.topcoder.com/challenges/5a70a6de-8189-48d5-a5d7-524852068ae5

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. PaymentStatus is changing according to the change in WorkingDays

![image](https://user-images.githubusercontent.com/55895538/123238751-b4d9bf80-d519-11eb-9d6a-ea8e007c6c68.png)
![image](https://user-images.githubusercontent.com/55895538/123238814-c4590880-d519-11eb-94c7-ba7fb76c1de2.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod with @nkumar-topcoder
