### ISSUE TITLE
[$10] We should not be able to set "Working Days" value less then "daysPaid"

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#26]
When we update the value inside the "Working days" field, at the moment the minimal value is 0. Though we added one more field to the Work Periods `daysPaid`. We should not be able to set value in the "Working Days" less then "daysPaid".

Don't forget to list this field in the `fields` to get it form the server.

**Comment by maxceem** [comment]
Implemented and works good.

**Comment by maxceem** [comment]
paid via https://www.topcoder.com/challenges/9314936a-a802-4eb8-b654-bf61be619582

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Not able to set value less than daysPaid.

![image](https://user-images.githubusercontent.com/55895538/123227834-ed749b80-d50f-11eb-8e72-00f9f217958a.png)

**Comment by sandhiyakavi** [comment]
Verified on PRod Env with @nkumar-topcoder
