### ISSUE TITLE
[$25] Add "Total Paid" column

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#27]
Add one more column named "Total Paid" on the right of the "Weekly Rate" Column.

This column should show the value in the next shape: `{formatDollar(WorkPeriod.paymentTotal}} ({WorkPeriod.daysPaid})`

Examples:
- `$0 (0)` - means $0 dollars paid for 0 days
- `$1000.00 (1)` - means $1000 dollars paid for 1 day
- `$500.00 (5)` means $500 dollars paid for 5 days

Make the `(X)` gray color, so we are showing days in gray.

This column should be sortable by the "paymentTotal".

Also, inside Resource Details show Total Paid with days instead of member rate. And we would show the Payment Popover when we click this value of total paid.

![image](https://user-images.githubusercontent.com/146016/122218312-ff729080-ceb6-11eb-868c-1649f1710d71.png)

**Comment by maxceem** [comment]
Added and works good.

**Comment by maxceem** [comment]
paid via https://www.topcoder.com/challenges/9314936a-a802-4eb8-b654-bf61be619582

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/123231740-7214e900-d513-11eb-8efc-5cc273f0ab59.png)

![image](https://user-images.githubusercontent.com/55895538/123231640-59a4ce80-d513-11eb-922c-35f3f3884ef1.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
