### ISSUE TITLE
[$60] Reflect in URL all the filters, selected dates, page and perPage

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#30]
At the moment we can apply various filters, select dates, choose perPage and select page. But if after that we reload the page, all our selected filters, page and so on reset.

We all of them to be reflected in the URL as query params like 
```
https://platform.topcoder-dev.com/taas-admin/work-periods?perPage=10&page=2&startDate=2021-10-01&userHandle=maxceem&paymentStatus=completed,pending
```

- If we load page by this URL directly all the filters, page and so on should be set as per URL
- Back/Forward browser buttons should work correctly, so if change page or filter, and then click Back, we should go to the previous filter/page

**Comment by maxceem** [comment]
works good

paid via https://www.topcoder.com/challenges/532cfb8a-2ea5-4310-82b1-62554c31ae4f

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. URL is reflecting all the filters and selections applied.

https://platform.topcoder-dev.com/taas-admin/work-periods?startDate=2021-06-20&status=completed&user=sachintop876&by=payment_total&order=desc&perPage=50&page=1
https://platform.topcoder-dev.com/taas-admin/work-periods?startDate=2021-06-20&status=completed,partially_completed,in_progress,no_days,pending&onlyFailed=y&by=start_date&order=desc&perPage=100&page=1

**Comment by sandhiyakavi** [comment]
Verified on Prod Env
