### ISSUE TITLE
[$40] Extend Payments Popover

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#35]
At the moment Payments Popover only shows Challenge id with copy and new tab buttons:

![image](https://user-images.githubusercontent.com/146016/122371860-e0ccd200-cf68-11eb-8d9b-e6d6dde6c98c.png)

We want to update it to show the table with the next columns:

- "Challenge ID" - show what we show now: challenge id link with two icons (keep it short like now) and add `...` when cut it.
- "Weekly Rate" - `memberRate` as dollar value, ex: `$1000.00`
- "Days" - `days` as a number, ex: `2`
- "Amount" - `amount` as dollar value, ex: `$400.00`
- "Status" - status show as a label, possible values: `completed` (#0ab88a), `scheduled` (#9d41c9), `in-progress` (#9d41c9), `failed` (#E90C5A), `cancelled` (#aaa) - Preferable reuse PaymentStatus component.

- No sorting is needed. Keep the style of this table as simple as possible, so we keep this popover as small as possible.

- Make the Total Paid value dashed if there is at least one payment so we know that we can click it:

   ![image](https://user-images.githubusercontent.com/146016/122380163-42dd0580-cf70-11eb-816a-023933ff4ea8.png)

**Comment by maxceem** [comment]
works good

paid via https://www.topcoder.com/challenges/cac94a1e-2aea-471b-95c2-dba2ba3c20cc

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/123237219-6d9eff00-d518-11eb-81da-03341484687b.png)

**Comment by sandhiyakavi** [comment]
Verified on PRod Env with @nkumar-topcoder
