### ISSUE TITLE
[$50] We should not allow increasing Working Days more than fit Resource Booking

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#37]
![image](https://user-images.githubusercontent.com/146016/122386305-702cb200-cf76-11eb-8418-1588305dbad6.png)

To implement this we have to create a reusable method which would return maximum allowed `daysWorked` for the WorkPeriod inside Resource Booking.

- The logic how we calculate `daysWorked` is described here https://github.com/topcoder-platform/taas-apis/wiki/Work-Periods-(WP)-Automation-and-Constraints#resourcebooking-is-created
- Also, we implemented a similar logic sever-side which may be used for reference https://github.com/topcoder-platform/taas-apis/blob/dev/src/common/helper.js#L1776-L1810 (note, that on server this method calculates all work periods for the ResourceBookings, but we need just to get the maximum allowed daysWorked for one Work Period)
- After having this method we should not allow to increase the Working Days more than possible value for each Work Period.

Tooltips:
- we already cannot decrease the number of working days to be less than daysPaid
- we have to explain to the user why they cannot decrease or increase the working days number by showing the reason in Tooltip
- to do so we have to show tooltip with the reason when the user hover mouse on the `-` or `+` buttons (only when they cannot press them):
   - `Cannot decrease "Working Days" to less than day already paid: ${daysPaid}`
   - `Cannot increase "Working Days" because the end date of the Resource Booking is ${RB.endDate}`

**Comment by maxceem** [comment]
Additionally disabled `decrease` button when the current value is `0` because we cannot make it less. We don't show tooltip in such case, because the reason for disabling button is clear.

**Comment by sandhiyakavi** [comment]
@maxceem I am able to see some '+' and '-' are slightly bolder than others.
![image](https://user-images.githubusercontent.com/55895538/124568924-6cf35a80-de80-11eb-9266-38b2f568ad37.png)

Other than above, functionality wise everything is working fine.
![image](https://user-images.githubusercontent.com/55895538/124566166-c60dbf00-de7d-11eb-930d-b9993d3842c4.png)
![image](https://user-images.githubusercontent.com/55895538/124566808-5815c780-de7e-11eb-89de-816adbb5c28e.png)
![image](https://user-images.githubusercontent.com/55895538/124567356-e427ef00-de7e-11eb-94a6-ab27c14180b4.png)

**Comment by maxceem** [comment]
@sandhiyakavi I believe the issue with bolder `-` and `+` is a different existent issue and it's not connected with the functionality we implemented in this issue. Can we track it separately? Also, could you, please, mention your browser and operation system, I believe it only happens on some OS and browser, as it doesn't happen to me.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/022e449b-b58c-4153-a07e-218d2a4c8801

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
