### ISSUE TITLE
[$175] Provide Job Title and ProjectId info for teamname

### ISSUE THREAD

**Issue by nkumar-topcoder** [topcoder-platform/micro-frontends-taas-admin-app#38]
Additional Info during payment shall help end user  to which `project id` and to which  `Job Title` the `Topcoder handle` belongs to.

Hence 

- When `user` moves mouse over `Topcoder  handle` then provide  Tool Tip `Job title`
- Same way when `user` moves mouse over `Team Name` then provide  Tool Tip `Project id`

![image](https://user-images.githubusercontent.com/33625707/122528405-eb0ad100-d039-11eb-8c94-464c76d7cce9.png)

**Comment by maxceem** [comment]
Sum up:
- Implement a reusable `Tooltip` component using the library `react-popper` which we already use for other popovers (don't add a new library).
- We should be able to use this library whenever we want to show Tooltips like:
    ```jsx
    <Tooltip content={<WhatToShowInsideTooltip />}><Anyting></Anything></Tooltip>
    ```
    - When we hover `<Anything></Anything>` with mouse show a tooltip with the `<WhatToShowInsideTooltip />` inside.
- Tooltip should have the same design as popover, see https://platform.topcoder-dev.com/taas-admin/work-periods?startDate=2021-06-27&status=completed&by=user_handle&order=asc&perPage=10&page=1 
    
   ![image](https://user-images.githubusercontent.com/146016/123918458-9138ce00-d98c-11eb-9d63-1c7054781a1a.png)
   
   - but also, it has to have the arrow, see `react-popper` documentation on how to add it https://popper.js.org/docs/v2/modifiers/arrow/

**Comment by MadOPcode** [comment]
@maxceem should the tooltip with project id contain the URL to the project? If so could you post the template for this URL?

**Comment by maxceem** [comment]
No need for now. If needed we could add the link inside the table column directly not in tooltip

**Comment by maxceem** [comment]
Implementation took care about many small details like:
- allow enter mouse into Tooltip and select text there
- show all the errors in Tooltip not only one of them
- nicely support dynamic content of the Tooltip

So I'm increasing the prize to $175 for this task.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/124450853-ca73a280-ddbf-11eb-96b5-a29ef83ff260.png)

![image](https://user-images.githubusercontent.com/55895538/124450943-e119f980-ddbf-11eb-8fcd-a6d178d647ee.png)

![image](https://user-images.githubusercontent.com/55895538/124450994-f000ac00-ddbf-11eb-9511-e912c3dec193.png)

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/b79e1ff2-0594-4edb-8347-087b9f460f96

**Comment by sandhiyakavi** [comment]
verified on Prod Env with @nkumar-topcoder
