### ISSUE TITLE
[$5] UI issue: Page extends past edge of screen

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#45]
Description:

The Taas Admin app page extends past edge of screen where as the micro-frontends top navigation bar is not.It creates a blank space there.

![image](https://user-images.githubusercontent.com/55895538/122892765-a4421180-d380-11eb-8e18-610a1d105d51.png)

**Comment by maxceem** [comment]
This issue is due to small screen size. The table is quite big and we don't have a good UI design on how to adapt it for smaller screens. We could think about it.

**Comment by maxceem** [comment]
Sum up:
- When we shrink the browser window and there is no not enough horizontal space of the table. The horizontal scroll should appear only for table:

   ![image](https://user-images.githubusercontent.com/146016/123917005-f8558300-d98a-11eb-81d4-c9a785b0f0f1.png)

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/27ac604f-87de-42ef-bb2f-82d0a46da37a

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Displaying correctly

![image](https://user-images.githubusercontent.com/55895538/124865206-30953b00-dff5-11eb-87f8-b5c144694c56.png)

**Comment by sandhiyakavi** [comment]
verified on Prod Env with @nkumar-topcoder
