### ISSUE TITLE
[$5] Messages for single resource are in plural form.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#46]
Description:

The messages displayed in Taas Admin app are all in plural form. Can we display the Message like below? so that it would be common for both singular as well as plural content.

sample: "Payment in progress for 1 resource(s)"

<img width="959" alt="plural_problemn" src="https://user-images.githubusercontent.com/55895538/123042681-24747f80-d432-11eb-9060-9fb9b2057199.png">

**Comment by maxceem** [comment]
Sum up:
- Copy/paste the helper method [formatPlural](https://github.com/topcoder-platform/taas-app/blob/dev/src/utils/format.js#L20-L29) to this repository.
- Apply it in the messages:
   - when process 1 or several payments on one page
   - when process payments for ALL records

**Comment by sandhiyakavi** [comment]
@maxceem If we check select all and only one record is available then in that case it is still displaying in plural form.

![image](https://user-images.githubusercontent.com/55895538/124460006-c8164600-ddc9-11eb-9c55-eacf8056c0a8.png)

Other than above, others are displaying fine.
![image](https://user-images.githubusercontent.com/55895538/124459482-20991380-ddc9-11eb-9d7b-8a7bc844415b.png)
![image](https://user-images.githubusercontent.com/55895538/124459602-42929600-ddc9-11eb-9a3f-f4bfc49ee566.png)

**Comment by maxceem** [comment]
@sandhiyakavi fixed plural form when selecting.

**Comment by sandhiyakavi** [comment]
@maxceem Still it is denoting plural '1 record on this page are selected'

<img width="956" alt="still_denoting_plural" src="https://user-images.githubusercontent.com/55895538/124548690-057de080-de69-11eb-870e-6f90b7627e25.png">

**Comment by maxceem** [comment]
@sandhiyakavi `is` / `are` fixed now.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/124569361-d83d2c80-de80-11eb-9a2f-76c86110fe83.png)
![image](https://user-images.githubusercontent.com/55895538/124569471-f2770a80-de80-11eb-92a1-892f39fc498f.png)
![image](https://user-images.githubusercontent.com/55895538/124569585-0c185200-de81-11eb-902a-0a4ce50d9ecb.png)
![image](https://user-images.githubusercontent.com/55895538/124569749-2fdb9800-de81-11eb-8b83-08412e490140.png)

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/b14afb84-d47b-4aca-80af-2972780c88f2

**Comment by sandhiyakavi** [comment]
verified on Prod Env with @nkumar-topcoder
