### ISSUE TITLE
[$30] Nice to have: Changes for Working Days field

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#50]
Description:

1. Currently if we change the daysWorked for a resource, there is no way to ensure it's changed except refreshing. can we add a green colour blink or some checkmark near the field to denote it is updated to the server?

![image](https://user-images.githubusercontent.com/55895538/123383171-d2686100-d5cd-11eb-8b94-ceec811e30dc.png)

2. Also is it possible to add some form of warning for the user to know that if the daysworked set (if user sets the days) for the first, second of first, last and second of last WP's are subjected to change if there is Change in the Resource Booking dates? Otherwise if user sets daysworked and then if RB dates changed, the daysworked will also be changed. User won't be aware of it.

**Comment by maxceem** [comment]
> Also is it possible to add some form of warning for the user to know that if the daysworked set (if user sets the days) for the first, second of first, last and second of last WP's are subjected to change if there is Change in the Resource Booking dates? Otherwise if user sets daysworked and then if RB dates changed, the daysworked will also be changed. User won't be aware of it.

@sandhiyakavi I think if we add some message for the first and last WPs it would be not enough. Because if we change RB dates for example in half, then half of the WPs would be removed and WP which would be the new last/first one, would be also updated, even though, before it was in the middle.

So far I don't see a good solution for such edge cases. I think what we can do, is log this issue separately, and we could try to discuss it with Will or other end users of the TaaS Admin App. We could learn from them their usage patterns, or maybe they would have some idea regarding this, how do they feel would be natural for them.

**Comment by maxceem** [comment]
Sum up:

- For now we would only implement the first part of this issue.
- When we change Working Days, we send the API request to the server. If request failed, we already show the error toastr.
   - if the request is successful we have to indicate it by showing the green checkmar in the green circle with some animation, for example this one https://codepen.io/kuvinod5/pen/WNvzazr
   - but use our green color `#137D60`
   - this checkmark should be show next to the Wokring Days input field like this 
      
     ![image](https://user-images.githubusercontent.com/146016/123939943-5db46e80-d9a1-11eb-9f3f-0f392cb9ef3c.png)
     
  - after 2 seconds (this time should be configurable) this checkbarm should fade away.

**Comment by sandhiyakavi** [comment]
@maxceem Currently if we try to increase WorkingDays beyond its fitting to the RB dates,error message is getting displayed but if we try to again change it back to its previous number(without refreshing), the green tick mark is getting displayed which should not happen as the number is not changed in this case.


https://user-images.githubusercontent.com/55895538/124448821-cd6d9380-ddbd-11eb-917c-562ea955b25c.mp4

**Comment by maxceem** [comment]
@sandhiyakavi this is a bit tricky issue.

The reason for this, when we increase the number it send to the server and gets error, but visually, the number stays as increased. When we decrease it back to previous value we send request to the server again, and this time server returns success - actually value is not changed we just send request to set the same value which is already there.

So the green tick kind of works correctly, it is shown when request is successful.

I'm not sure how it would be better to handle such case if error happened, but if you think we should do something about, I suggest logging a separate issue for this case.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/124457605-f0e90c00-ddc6-11eb-8f4b-4ca779f62b35.png)

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/dd90e9bb-eff7-4cbe-aa67-0c3791379de0

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
