### ISSUE TITLE
[$10] Able to process payment more than once if the process payment button is pressed continuously more than once.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#53]
Description:

If we click the process payment button immediately again after clicking the first time, able to schedule the payment more than once. As a result we are able to pay more than the  daysWorked.

sample: https://platform.topcoder-dev.com/taas-admin/work-periods?startDate=2023-07-30&by=user_handle&order=asc&perPage=50&page=1

Steps to Reproduce:
1. Select the Resources that needs to process payment.
2. Click the process payment button like double click/triple click
3. Observe the Payment is getting scheduled more than once.

<img width="960" alt="wrongy" src="https://user-images.githubusercontent.com/55895538/123606831-4443e300-d838-11eb-9297-e34ef6af41b9.png">
<img width="960" alt="wrongy_2" src="https://user-images.githubusercontent.com/55895538/123606846-47d76a00-d838-11eb-8e7c-968ffa0c92ed.png">
<img width="850" alt="multiple_schedule" src="https://user-images.githubusercontent.com/55895538/123606857-4a39c400-d838-11eb-9351-76b932c9735f.png">

<img width="860" alt="wrongy_4" src="https://user-images.githubusercontent.com/55895538/123607592-01363f80-d839-11eb-954b-925bcd03d2f2.png">

**Comment by maxceem** [comment]
Sum up:
- `Process payment` button should got disabled until the server request is finished, so we cannot click it multiple times until the server returns the response.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Not able to schedule more than once

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/f4366c9a-e111-46d2-8cb6-fd8516f0b136

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
