### ISSUE TITLE
Show error details when all payments are failed

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#55]
At the moment when some payments are failed and some are successful we are showing error details for failed payments:

![image](https://user-images.githubusercontent.com/146016/124076727-5186ea80-da4f-11eb-9636-472f1ea100bf.png)

But if all payments are failed we are not showing error details:

![image](https://user-images.githubusercontent.com/146016/124076645-374d0c80-da4f-11eb-9524-48b338bfd338.png)

We should show error details in both cases. So we always would like to know the error details of the failed payments.

**Comment by MadOPcode** [comment]
@maxceem to clarify, should the error details be shown as described in #54?

**Comment by maxceem** [comment]
@MadOPcode no. I mean in the toastr. See screenshots above:
- when some of the payments is success - we show error details 
-but when all payments are failed, we don't show error details

So we have to show error details inside toastr even if all payments are failed like this in toastr: 

![image](https://user-images.githubusercontent.com/146016/124361795-9a01fc00-dc39-11eb-8203-19eb3a758046.png)

**Comment by MadOPcode** [comment]
@maxceem but in #54 you wrote:
> Remove the list of error messages from the toastr. Only show how many payment were successfully scheduled and how many failed, but without the list of error messages.

So should the error messages be both in the popovers near checkboxes and in the toastrs or only in the popovers?

**Comment by maxceem** [comment]
Ah, you are right. So the current issue is not needed anymore. As we would not show error messages in toaster anymore. We would always show them near checkboxes.

Please, ignore this issue.

**Comment by maxceem** [comment]
This is no longer needed, as per https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/54 we are showing errors inside the rows instead of toastrt.
