### ISSUE TITLE
[$100] UI to cancel payments

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#56]
We would like to be able to cancel payments if we need to.

![image](https://user-images.githubusercontent.com/146016/124078551-a8d98a80-da50-11eb-9a47-c70f256e8bd7.png)

- Inside Payments Popup add button one more column with no title. And in that column add `red` button `Cancel`.
  - `Cancel` button should be disabled for the payments in status `in-progres` - other statuses we can cancel.
- When we click it, show Confirmation Modal window which should look like this:
   
   ![image](https://user-images.githubusercontent.com/146016/124079368-b17e9080-da51-11eb-89d7-f92913e50e40.png)

   - use styles and common code to show modal windows from TaaS App (you can see this modal here https://platform.topcoder-dev.com/taas/myteams/17975/access if you click "x" to remove member)

   - if we click `cancel cencelling` then just hide confirmation window
   - if we click `mark as cancelled` then show **loading indicator** and title "Marking as cancelled...", same as in TaaS App      
      
       ![image](https://user-images.githubusercontent.com/146016/124080680-4fbf2600-da53-11eb-950d-2ad627dd37cc.png)
       
      - if request failed, then keep showing confirmation window, hide loading indicator inside it, and show text and buttons again so user can try to click `mark as cancelled` again, the same time show red toastr with error message from the server
      - after canceling payment the WP paymentStatus may change. So after the payment is cancelled reload data for the WP. It may happen that data on the server is not yet updated. So add a configured artifical delay after the success request to cancel payment, so it would be like this:
      - if the request is successful, then:
         - update payment data in the Payment Popup using server response
         - add an artificial delay of 3 seconds (configurable) and show loading indicator for 3 seconds more
         - after that, keep showing loading indicator and send request to reload one row of WP, and update data for the WP row in table
         - hide confirmation window and show green toastr which says `Payment ${amount} for ${userHandle} was marked as "cancelled"`

**Comment by sandhiyakavi** [comment]
@maxceem For cancel payments, the 'cancel' button is not active for 'scheduled' status and active for 'in-progress' status but it should be active for 'scheduled' and inactive for 'in-progress'

<img width="960" alt="scheduled cannot cancel" src="https://user-images.githubusercontent.com/55895538/124547289-df574100-de66-11eb-84fc-e76506c4f8b9.png">
<img width="960" alt="Screenshot_3" src="https://user-images.githubusercontent.com/55895538/124547335-eed68a00-de66-11eb-9acd-456f5a86cdeb.png">
<img width="960" alt="cancel error" src="https://user-images.githubusercontent.com/55895538/124547339-ef6f2080-de66-11eb-977f-70efbdf9d815.png">

**Comment by maxceem** [comment]
@sandhiyakavi fixed.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Able to cancel payments for all status other than 'in-progress'
![image](https://user-images.githubusercontent.com/55895538/124572192-6b776180-de83-11eb-9f84-c0bbf34cddd6.png)

![image](https://user-images.githubusercontent.com/55895538/124572117-5c90af00-de83-11eb-8426-4214e05f036d.png)
![image](https://user-images.githubusercontent.com/55895538/124572884-fb1d1000-de83-11eb-9b1a-310ed4058118.png)

![image](https://user-images.githubusercontent.com/55895538/124572425-9d88c380-de83-11eb-9f48-deb47b80befd.png)

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/449bf8d0-61f5-4d51-83dc-4481b145334d

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
