### ISSUE TITLE
[$30] Better wordings for showing Permission restrictions

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#6]
Description:

Users other than BookingManager/Admin if they try to access the Taas Admin app. Now the text "Error: You don't have access to view memberRate" is displayed.

![image](https://user-images.githubusercontent.com/55895538/120307939-83047d00-c30e-11eb-9a75-ec42f5d786f3.png)

Instead of that can we have other text like "You don't have permission to access this page" or hide the "TAAS admin" option itself in the top nav bar ?

**Comment by nkumar-topcoder** [comment]
@sandhiyakavi for user other than BM/admin role - plan is -  not show `taas-admin` icon. This will be implemented.
cc @maxceem

**Comment by maxceem** [comment]
Summary:
- To avoid such issues, we should check user permissions to see the page before making any API request.
- To support such a feature in a general way we can update `withAuthentication` HOC, so it support the second argument `roles` where we should pass user roles who can access this page. If auth user don't have such roles, we should show error.

Example:
  - For a page with Work Periods [here ](https://github.com/topcoder-platform/micro-frontends-taas-admin-app/blob/dev/src/routes/WorkPeriods/index.jsx#L55) we can update to `export default withAuthentication(WorkPeriods, ADMIN_ROLES);
  - Where `ADMIN_ROLES` is a constant with value `['bookingmanager', 'administrator']`
  - And update the code of `withAuthentication` to be:
     ```js
     export default function withAuthentication(Component, roles) {
     ```

     and inside, as soon as we get the user details, we should check if user has at least one role, and if no, then show error: `You don't have permissions to access this page`.

**Comment by maxceem** [comment]
@MadOPcode would you like to handle it as a private task? The prize is mentioned in the issue description - $30.

Working branch: `dev`
Submission: PR

**Comment by MadOPcode** [comment]
@maxceem yes I'm ready to make a PR.

**Comment by maxceem** [comment]
ok, please, make PR when it's ready

**Comment by MadOPcode** [comment]
@maxceem although I have a question first. The HOC component withAuthentication either displays or hides the whole page including the sidebar with navigation menu. So if the user doesn't have required role(s) the navigation menu will not be on the page. Should the sidebar with navigation menu still be visible if the user does not have required role(s)?

**Comment by maxceem** [comment]
That's a good question. Let's keep it simple for now - the whole page would be hidden with sidebar, if wee need to keep sidebar visible in the future we would think for another solution.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/120621954-59c42800-c499-11eb-9ddd-bda7e50ee4b6.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
