### ISSUE TITLE
[$5] Member rate displayed as Integer in UI instead of floating point number.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#7]
Description:

Weekly rate (Member rate) is displayed as Integer in UI instead of floating point number.

![image](https://user-images.githubusercontent.com/55895538/120313152-94508800-c314-11eb-92cd-d29fac0b3477.png)
![image](https://user-images.githubusercontent.com/55895538/120313218-a6322b00-c314-11eb-9a79-9aef7d4a4edb.png)

**Comment by maxceem** [comment]
Sum up:
- We have to display Member Rate with 2 digits after the point, like `1,200.00`, `11.23` and so on.

**Comment by maxceem** [comment]
@MadOPcode would you like to handle it as a private task? Prize $5.

**Comment by MadOPcode** [comment]
@maxceem yes I'm ready to make a PR.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/120623410-ab20e700-c49a-11eb-9bef-763445b01f9a.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
