### ISSUE TITLE
Sorting by Topcoder handle is not working correctly.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#8]
Description:
Sorting by Topcoder handle is not working correctly.

![image (1)](https://user-images.githubusercontent.com/55895538/120317550-b993c500-c319-11eb-9737-d2cbd2b73204.png)

**Comment by nkumar-topcoder** [comment]
@sandhiyakavi please check - we have fixed and re-indexed

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Sorting correctly now

![image](https://user-images.githubusercontent.com/55895538/120417475-d8d23700-c399-11eb-977a-4ba9464e4384.png)

**Comment by maxceem** [comment]
Closing as it was only on DEV.
