### ISSUE TITLE
Update BA for already processed payments of the Work Period

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/micro-frontends-taas-admin-app#81]
### Background

Managers can process payments for Work Periods. Money for the payments comes from the Billing Account which is associated with Resource Booking:

![image](https://user-images.githubusercontent.com/146016/127316605-bde4f465-ac7d-4c80-b3eb-9ba5a0237a11.png)

Sometimes Managers process payments using the wrong billing account. And they would like to update the billing account for all payments which are done during the current Work Period (week). 

### Task

- Add `Actions` dropdown menu to each of the row in the table with 1 option: `Update BA for payments` (or add this option if `Actions` is already implemented via this task https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/82)

     <img width="1440" alt="Additional BA Modal (2)" src="https://user-images.githubusercontent.com/146016/127319790-dff4be8b-00b8-4a32-98b0-ca6e6c5d7866.png">

   - The actions dropdown is already implemented in https://github.com/topcoder-platform/taas-app see demo page https://platform.topcoder-dev.com/taas/myteams/18102. Please, port it from there.  
   Or reuse it if it was already ported during another task https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/80 or https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/82.
   
- When we click `Update BA for payments` show a modal:   

   <img width="1440" alt="Additional BA Modal (1)" src="https://user-images.githubusercontent.com/146016/127319647-2386c2ae-6d81-485e-bd14-e714000d4eb4.png">

    - For modal, use the same design as for adding payment: https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/82
    - Inside `Current BA used` list the billing accounts which were used for payments at the moment which would be updated

- If we click `Cancel` or `X` just close the modal.
- if we click `Update BA for payments` show a loading indicator inside the modal OR just disable the fields and all the buttons while sending request to the server.
  - if the request was successful, show a successful green toastr and close the modal which says, `Billing account was successfully updated for all the payments`:
     ![image](https://user-images.githubusercontent.com/146016/127200618-e07fd75f-2691-4135-bd5e-bc9409305660.png)
  - in case of error show error red toastr with error message from the server, but keep the modal open so user can try updating payment again
        
### API

- API has been implemented to support updating a billing account for multiple payments at once https://github.com/topcoder-platform/taas-apis/issues/433
- We have to send a request to update Billing Account for all the payments inside the Work Period by the next request https://topcoder-platform.github.io/taas-apis/#/WorkPeriodPayments/patch_work_period_payments_bulk

**Comment by sandhiyakavi** [comment]
@maxceem Below are some of the issues found,

1. No BA option is getting displayed normally in the dropdown, except the one assigned to the RB through backend. 

![image](https://user-images.githubusercontent.com/55895538/129512370-1e47536b-b780-4065-9a4a-f9ae30b19ff6.png)

2. If we assign some invalid/expired BA to the RB, no error is shown. The payment is going to completed status / BA updated for completed challenges without any error. But if the same BA is assigned at the project level, the payment is failing.
sample Expired BA used: 80000071
is that possible to validate the BA at RB level as the payment is based on the BA at RB level?

![image](https://user-images.githubusercontent.com/55895538/129517759-4939ab68-da4c-420a-948a-74d09c317120.png)

**Comment by maxceem** [comment]
@sandhiyakavi 

1. In this list we are show the same list of BA which we show for RB:

   ![image](https://user-images.githubusercontent.com/146016/129530764-b0254f71-89ca-4bd4-bb13-b8228d72bde0.png)
   
   ![image](https://user-images.githubusercontent.com/146016/129530796-5f836a97-6b6b-4a5b-a321-1a1208ca8cbb.png)
   
   So if for RB we are showing only 1 BA, then when updating we also showing only 1 BA.
   
   NOTE: the logic behind showing the list of BA is quite tricky:
       - user has to have BAs available to they
       - user must be Topcoder Admin, or be a member of the Topcoder Team inside the Project associated with Resource Booking
       
     To verify if we are showing correct BAs, you may open project in Connect and see the list of BAs there, it should be the same in all 3 places: Connect, RB, and Update BA Model.
      
    ![image](https://user-images.githubusercontent.com/146016/129531163-b19303e3-8ece-44ca-99f2-089c77a5fa54.png)
    
2. Theoretically we can try add such check, but I'm not sure if that's needed. Imagine the next situation:
     - we process payments using 1 BA
     - after some we realised that we used wrong BA, so we want to set the correct BA, but correct BA at this moment is expired now. I guess we would still would like to update BA in the past payments even though the BA is not more active, just to have correct history.
     
     If you believe we should validate it anyway, I suggest tracking this separately as an enhancement requirement.

**Comment by sandhiyakavi** [comment]
Below scenarios are tested  in Dev Env.

1. Verify Update BA for payments is shown in dropdown Actions only if there is already some payment processed.
2. Verify whether modal opens for Update BA for payments
3. Verify whether the contents Work period, ResourceBooking, Job name, Team name, Current BA's used are correctly displayed.
4. Verify whether all the BA's used for the WP are displayed in Current BA's used.
5. Verify whether BA are populated from the New Billing Account dropdown
6. Verify whether BA updated on clicking  'Update BA for payments' button.
7. Verify whether payment is not processed on clicking cancel or 'x' button.
8. Verify whether toaster message is displayed for processing payment 'Billing account was successfully updated for all the payments:'
9. Verify whether BA already updated was displayed if the BA was already displayed for all WP payments.

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.

cc: @nkumar-topcoder
