### ISSUE TITLE
Directing to first page if sorting applied to table contents in pages other than first page

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#9]
Description:

User is getting directing to first page if sorting applied to table contents in pages other than first page.

https://user-images.githubusercontent.com/55895538/120318143-77b74e80-c31a-11eb-8c01-8afe58c80765.mp4

**Comment by maxceem** [comment]
I think this is expected behavior.

If a user changes sort order he would sort the data for the whole table, so data on the 2nd page would be completely changed. So it makes sense to start from the first page if the sorting order is changed.

**Comment by sandhiyakavi** [comment]
Closing the issue as its expected.
